blank_issues_enabled: false
# contact_links:
#   - name: Contact Rainbow Devs
#     url: https://example.com/contact
#     about: For contact outside of our Slack, contact Rainbow Devs through our website.
